# Generated by Django 4.1.7 on 2023-03-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_alter_space_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='code',
            field=models.CharField(db_index=True, default='1dddbe2a59154a4990ab75eddeaac343', max_length=32, primary_key=True, serialize=False),
        ),
    ]
