version: '3'

volumes:
  cocode_dev_postgres_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    image: cocode_dev_django
    container_name: cocode_dev_django
    platform: linux/x86_64
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    ports:
      - "8000:8000"
    command: /start

  redis:
    image: redis:6
    container_name: cocode_dev_redis

  postgres:
    image: postgres:14
    container_name: cocode_dev_postgres
    volumes:
      - cocode_dev_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.envs/.postgres

  ui:
    build:
      context: .
      dockerfile: ./compose/dev/ui/Dockerfile
    image: cocode_dev_ui
    container_name: cocode_dev_ui
    depends_on:
      - django
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend:z
