# Generated by Django 4.1.7 on 2023-03-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='code',
            field=models.CharField(db_index=True, default='37f06182739f46aeaa59da00fde489c2', max_length=32, primary_key=True, serialize=False),
        ),
    ]
