# Generated by Django 4.1.7 on 2023-03-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_alter_space_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='code',
            field=models.CharField(db_index=True, default='80c78187b6f1470b9d10c5100fad308a', max_length=32, primary_key=True, serialize=False),
        ),
    ]
