# Generated by Django 4.1.7 on 2023-03-09 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space', '0002_alter_space_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBrowserNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('is_directory', models.BooleanField(default=True, verbose_name='Directory?')),
                ('language', models.CharField(blank=True, max_length=25, null=True, verbose_name='Programing Language')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Value')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='File Size')),
                ('is_root', models.BooleanField(default=False, verbose_name='Root?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='file_browser.filebrowsernode')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_folder', to='space.space')),
            ],
            options={
                'unique_together': {('space', 'name')},
            },
        ),
    ]
