# Generated by Django 4.1.7 on 2023-03-09 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_alter_space_code'),
        ('file_browser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebrowsernode',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_folder', to='space.space'),
        ),
    ]
